version: '2.0'
services:
  server:
    container_name: server
    build: .
    volumes:
      - ./src:/usr/app/src
      - D:/Wallpapers/food:/usr/app/background
    ports:
      - "8626:8626"
    env_file:
      - .env.local
    links:
      - mongodb
      - redis
  mongodb:
    container_name: mongodb
    image: mongo
  redis:
    container_name: redis
    image: redis
    command: redis-server
